// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jactfilrcgpkjhpietuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphY3RmaWxyY2dwa2pocGlldHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MDc1OTUsImV4cCI6MjA1OTQ4MzU5NX0.vySbQ4wlj5_DQFD3v9TqWo5qWtnHmfO2aL2o05WRpxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);